<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          Report | <a href="#" onClick="javascript:history.go(-1)">back</a>
        </h2>
    </x-slot>

<div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

<style type="text/css">
  .label-header h2{
    width: 100%;
    height: 35px;
    border-radius: 20px;
    background-color: #E0E0E0;
    color:black;
    margin-top: -10px;
  }
  .main td{
    font-size: 14px;
  }
  th{
    text-align: center;
  }
  .naration{
    width: 300px;
  }
</style>
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <p class="category"> Day End Detail Report</p>
      </div>
      <div class="card-body table-responsive">
        <form id="lockForm">
        <div class="row">
            <div class="col-md-3">
                <label>Select Date</label>
                <input type="date" class="form-control" name="startdate"><br>
            </div>
        </div>
        </form>
        <div class="row">
            <div class="col-md-4">
                <button class="btn btn-primary" name="btn" onclick="dayendDetail()">Generate Report</button>
            </div>
        </div><br><br>
        <div id="printableArea">
        <!-- <div class="row" >
          <div class="col-md-6">
            <ul>
                <li><strong>Day End Detail Report</strong></li>
                <li><label>Report: <span id="from">All</span></label></li>
            </ul>
          </div>
          <div class="col-md-6">
              <ul style="float: right">
                <li><strong>Generated by: <span id="uname">User</span></strong></li>
                <li><label>Day: <?php date_default_timezone_set("Asia/Karachi"); echo date("d-m-Y h:i:A");?></label></li>
            </ul>
          </div>
        </div> -->
        <div class="row">
        <table border="1" width="97%" align="center">
        <tr>
          <td width="28%">Print Date: <?php date_default_timezone_set("Asia/Karachi"); echo date("d/m/Y");?></td>
          <td style="text-align: center;font-size: 18px;font-weight: bold;"><i>{{ $company[0] }}</i>
          </td>
          <td style="float: right;">From: <span id="from"><?php echo date("d/m/Y"); ?></span></td>
        </tr>
        <tr>
          <td><span id="uname">{{$uname}}</span></td>
          <td style="text-align: center;">Dayend Detail Report</td>
          <td style="float: right;">To: <span id="to"></span></td>
        </tr>
      </table>
        </div><br>
        <div class="row">
          <div class="col-md-12">
            <div class="label-header">
                <center><h1 style="width: 100%; border-radius: 20px;background-color: #E0E0E0;color:black;padding: 10px;font-weight: bolder;font-size: 20px;margin-bottom: 5px;">Today Sale</h1></center>
            </div>
          </div>
        </div>
        <div class="">
            <form id="updateStock">
              @csrf
          <table class="table table-bordered" style="text-align: center;">
            <thead>
              <tr>
                <th>Sr#</th>
                <th>Sale#</th>
                <th>Barcode</th>
                <th>Customer</th>
                <th>Naration</th>
                <th>Total</th>
                <th>Paid</th>
                <th>Remaining</th>
              </tr>
            </thead>
            <tbody id="stock"></tbody>
          </table>
          <div class="row">
          <div class="col-md-12">
            <div class="label-header">
                <center><h1 style="width: 100%; border-radius: 20px;background-color: #E0E0E0;color:black;padding: 10px;font-weight: bolder;font-size: 20px;margin-bottom: 5px;">Today Purchase</h1></center>
            </div>
          </div>
        </div>
        <table class="table table-bordered" style="text-align: center;">
          <thead>
            <tr>
              <th>Sr#</th>
              <th>Purchase#</th>
              <th>Barcode</th>
              <th>Vender</th>
              <th>Naration</th>
              <th>Total</th>
              <th>Paid</th>
              <th>Remaining</th>
            </tr>
          </thead>
          <tbody id="stock2"></tbody>
          </table>
          <div class="row">
          <div class="col-md-12">
            <div class="label-header">
                <center><h1 style="width: 100%; border-radius: 20px;background-color: #E0E0E0;color:black;padding: 10px;font-weight: bolder;font-size: 20px;margin-bottom: 5px;">Today Cashin</h1></center>
            </div>
          </div>
        </div>
        <table class="table table-bordered" style="text-align: center;">
          <thead>
            <tr>
              <th>Sr#</th>
              <th>Invoice#</th>
              <th>Name</th>
              <th>Remarks</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody id="stock3"></tbody>
          </table>
          <div class="row">
          <div class="col-md-12">
            <div class="label-header">
                <center><h1 style="width: 100%; border-radius: 20px;background-color: #E0E0E0;color:black;padding: 10px;font-weight: bolder;font-size: 20px;margin-bottom: 5px;">Today Cashout</h1></center>
            </div>
          </div>
        </div>
        <table class="table table-bordered" style="text-align: center;">
          <thead>
            <tr>
              <th>Sr#</th>
              <th>Invoice#</th>
              <th>Name</th>
              <th>Remarks</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody id="stock4"></tbody>
          </table>

          <center><h6><span style="font-family: sans;"> Arbaz Ehsan;</span> 03137747660; arbazehsan988@gmail.com</h6></center>
        </form>
        </div>
        </div>
        <button onclick="printDiv('printableArea')" class="btn btn-info"> Print </button>
      </div>
    </div>
  </div>
</div>

    </div>
</div>
</x-app-layout>


<script type="text/javascript">
function dayendDetail(){
    $.ajax({
        type: "GET",
        url:"/getDayendDetailReport",
        data: $('#lockForm').serialize(),
        success:function(response) {
          //alert(response);
          var display = response;
          display = display.split(',');
          $('#stock').html(display[0]);
          $('#stock2').html(display[1]);
          $('#stock3').html(display[2]);
          $('#stock4').html(display[3]);
          $('#uname').html(display[4]);
        },
        error: function (error) {
          console.log(error);
          //alert(error);
          //nowuiDashboard.showNotification('top','center','danger',error);
        }
    });
}

function printDiv(divName) {
  var printContents = document.getElementById(divName).innerHTML;
  var originalContents = document.body.innerHTML;
  document.body.innerHTML = printContents;
  window.print();
  document.body.innerHTML = originalContents;
}

function popup(str,from){
  window.open('/salePrint/'+str,'popUpWindow','height=400,width=1000,left=50,top=50,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no, status=yes');
}
</script>
