<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          Report | <a href="#" onClick="javascript:history.go(-1)">back</a>
        </h2>
    </x-slot>

<div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

<style type="text/css">
  h6{
    font-weight: normal;
  }
</style>
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <p class="category"> Receivable Report</p>
      </div>
      <div class="card-body table-responsive">
        <form id="lockForm">
        <div class="row">
            <div class="col-md-3">
                <label>From Date</label>
                <input type="date" class="form-control" name="startdate"><br>
            </div>
            <div class="col-md-3">
                    <label>To Date</label>
                <input type="date" class="form-control" name="enddate" ><br>
            </div>
        </div>
        </form>
        <div class="row">
            <div class="col-md-4">
                <button class="btn btn-primary" name="btn" onclick="receivable()">Generate Report</button>
            </div>
        </div><br><br>
        <div id="printableArea">
        <!-- <div class="row" >
          <div class="col-md-6">
            <ul>
                <li><strong>Receivable Report</strong></li>
                <li><label>Report: <span id="from">All</span> to <span id="to">All</span></label></li>
                <li><label>Customer Name: <span id="cname"></span></label></li>
            </ul>
          </div>
          <div class="col-md-6">
              <ul style="float: right">
                <li><strong>Generated by: <span id="uname">User</span></strong></li>
                <li><label>Day: <?php date_default_timezone_set("Asia/Karachi"); echo date("d-m-Y h:i:A");?></label></li>
            </ul>
          </div>
        </div> -->
        <div class="row">
        <table border="1" width="97%" align="center">
        <tr>
          <td width="28%">Print Date: <?php date_default_timezone_set("Asia/Karachi"); echo date("d/m/Y");?></td>
          <td style="text-align: center;font-size: 18px;font-weight: bold;"><i>{{ $company[0] }}</i>
          </td>
          <td style="float: right;">From: <span id="from"><?php echo date("d/m/Y"); ?></span></td>
        </tr>
        <tr>
          <td><span id="uname">{{$uname}}</span></td>
          <td style="text-align: center;">Receivable Report</td>
          <td style="float: right;">To: <span id="to"></span></td>
        </tr>
      </table>
        </div>
        <div class="">
            <form id="updateStock"><br>
              @csrf
          <table class="table table-bordered" style="text-align: center;">
            <thead>
              <tr>
                <th>Sr#</th>
                <!-- <th>Date</th> -->
                <th>Title of A/C</th>
                <th>Receivables (Rs.)</th>
              </tr>
            </thead>
            <tbody id="stock"></tbody>
            <tr>
                <td colspan="1"></td><td class="pull-right"><b>Total</b></td>
                <td style="border:2px solid black;font-weight: bold;"><span id="sum"></span></td>
            </tr>
          </table>
          
          <!-- <center><h6><span style="font-family: sans;"> Arbaz Ehsan;</span> 03137747660; arbazehsan988@gmail.com</h6></center> -->
        </form>
        </div>
        </div>
        <button onclick="printDiv('printableArea')" class="btn btn-info"> Print </button>
      </div>
    </div>
  </div>
</div>

    </div>
</div>
</x-app-layout>


<script type="text/javascript">
function receivable(){
    $.ajax({
        type: "GET",
        url:"/getReceivableReport",
        data: $('#lockForm').serialize(),
        success:function(response) {
          //alert(response);
          var display = response;
          display = display.split(',');
          $('#stock').html(display[0]);
          $('#sum').html(display[1])
          $('#to').html(display[3]);
          if(display[2] !=""){
            $('#from').html(display[2]);
          }
        },
        error: function (error) {
          console.log(error);
          //alert(error);
          //nowuiDashboard.showNotification('top','center','danger',error);
        }
    });
}

function printDiv(divName) {
  var printContents = document.getElementById(divName).innerHTML;
  var originalContents = document.body.innerHTML;
  document.body.innerHTML = printContents;
  window.print();
  document.body.innerHTML = originalContents;
}

function popup(str,from){
  window.open('/salePrint/'+str,'popUpWindow','height=400,width=1000,left=50,top=50,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no, status=yes');
}
</script>
